# 站点名称
site_name: 'Deploy'
# 仓库链接
repo_url: https://github.com/ZJDoc/Deploy
# 作者
site_author: 'zhujian'
# 版权信息
copyright: '2021, zhujian'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 0.1.0
# 主题
theme: 
    # name: 'readthedocs'
    # name: 'mkdocs'
    name: 'material'
# markdown扩展
markdown_extensions:
  # 参考[MathJax](https://squidfunk.github.io/mkdocs-material/reference/mathjax/)，支持数学公式渲染
  - pymdownx.arithmatex:
      generic: true
    # 参考[Icons + Emojis](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/)，执行Markdown Emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# mathjax
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 导航
nav:
    - Home: index.md
    - 网络:
      - 引言: network/index.md
      - 基础:
        - IP地址: network/basic/ip地址.md
        - '路由器、交换机、集线器、中继器': network/basic/路由器-交换机-集线器-中继器.md
        - '局域网、广域网、互联网和私有专用网': network/basic/局域网-广域网-互联网-私有专用网.md
        - 网络体系结构: network/basic/网络体系结构.md
        - URL构成: network/basic/URL构成.md
        - DNS解析过程: network/basic/DNS解析过程.md
      - 进阶:
            - '[namesilo][dnspod]域名申请和解析': network/advanced/namesilo-dnspod-域名申请和解析.md
            - '[阿里云][域名解析]URL转发': network/advanced/阿里云-域名解析-URL转发.md
            - '[Ubuntu 18.04]wifi信息查询': network/advanced/ubuntu-18_04-wifi信息查询.md
            - '[Ubuntu 18.04][resolv.conf]公共DNS设置': network/advanced/ubuntu-18_04-公共DNS设置.md
            - '[Docker][Ubuntu 18.04]网络工具安装': network/advanced/docker-ubuntu-18_04-网络工具安装.md
            - '[nslookup]域名解析': network/advanced/nslookup-域名解析.md
            - '[netstat]端口查询': network/advanced/netstat-端口查询.md
            - '[nc]远程端口查询': network/advanced/nc-远程端口查询.md
    - 连接:
      - 内网穿透:
        - 引言: penetration/index.md
        - '[路由器]虚拟服务器': penetration/路由器-虚拟服务器.md
        - 花生壳: penetration/花生壳.md
        - n2n: 
          - n2n原理: penetration/n2n/n2n原理.md
          - n2n实现: penetration/n2n/n2n实现.md 
        - Ngrok:
          - 引言: penetration/ngrok/index.md
          - Ngrok实现: penetration/ngrok/ngrok实现.md
          - TCP和HTTP连接配置: penetration/ngrok/tcp-http-连接配置.md
          - 'Ubuntu Service实现': penetration/ngrok/ubuntu-service.md
          - Docker实现: penetration/ngrok/ngrok-docker.md
      - SSH:
        - 入门:
            - http和ssh协议: ssh/base/http和ssh协议.md
            - '[SSH]远程连接': ssh/base/ssh-远程连接.md
            - '[SSH]常用工具': ssh/base/ssh-常用工具.md
            - '[SSH]生成密钥': ssh/base/ssh-生成密钥.md
            - '[SSH]客户端配置文件': ssh/base/ssh-客户端配置文件.md
        - 进阶:
            - '禁用公钥检查': ssh/advanced/ssh-禁用公钥检查.md
            - 复制公钥到远程服务器: ssh/advanced/复制公钥到远程服务器.md
            - 添加私钥缓存: ssh/advanced/添加私钥缓存.md
            - '[ssh-agent]代理设置': ssh/advanced/ssh-agent-代理设置.md
            - '[SSH -L]端口转发': ssh/advanced/端口转发.md
        - ERROR: ssh/error.md
    - Web服务器:
      - Tomcat:
        - 关于Tomcat: tomcat/关于Tomcat.md
        - '[Ubuntu 16.02]Tomcat9安装': tomcat/ubuntu-16_02-tomcat9安装.md
        - 非root用户运行: tomcat/非root用户运行.md
      - Nginx:
        - 入门:
          - 安装: nginx/base/安装.md
          - 测试: nginx/base/测试.md
          - 配置: nginx/base/配置.md
          - 中文乱码: nginx/base/中文乱码.md
          - 托管网站: nginx/base/托管网站.md
        - 进阶:
          - '[阿里云]配置HTTPs': nginx/advanced/阿里云-配置https.md
          - '[腾讯云]配置HTTPs': nginx/advanced/腾讯云-配置https.md
          - 多域名配置同一端口: nginx/advanced/多域名配置同一端口.md
          - 反向代理: nginx/advanced/反向代理.md
          - '[译]NGINX Reverse Proxy': nginx/advanced/译-nginx-reverse-proxy.md
          - '[Docker]Nginx安装': nginx/advanced/docker-nginx.md
          - 文件共享服务: nginx/advanced/文件共享服务.md